chore: setup firebase
fvm dart pub global run flutterfire_cli:flutterfire configure --project=flutter-firebase-practic-636a5
i Found 9 Firebase projects. Selecting project flutter-firebase-practic-636a5.
✔ Which platforms should your configuration support (use arrow keys & space to select)? · android, ios
✔ Which Android application id (or package name) do you want to use for this configuration, e.g. 'com.example.app'? · com.sughimura.app
i Firebase android app com.sughimura.app is not registered on Firebase project flutter-firebase-practic-636a5.
i Registered a new Firebase android app on Firebase project flutter-firebase-practic-636a5.
i Firebase ios app com.example.flutterFirebasePractice is not registered on Firebase project flutter-firebase-practic-636a5.
i Registered a new Firebase ios app on Firebase project flutter-firebase-practic-636a5.
Exception: No version is set for command ruby
Consider adding one of the following versions in your config file at /Users/noritsugusughimura/.tool-versions
ruby 2.7.5